name: Run Hardhat Tests

on:
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull pre-deployed Geth image
        run: docker pull ghcr.io/${{ github.repository_owner }}/go-ethereum:devnet-with-contracts

      - name: Start Geth devnet with deployed contracts
        run: |
          docker run -d --name devnet -p 8545:8545 \
            ghcr.io/${{ github.repository_owner }}/go-ethereum:devnet-with-contracts \
            geth --http --http.addr 0.0.0.0 --http.port 8545 \
                 --http.api eth,net,web3,txpool,personal \
                 --dev --datadir /data

      - name: Wait for Geth
        run: |
          for i in {1..10}; do
            curl -s http://localhost:8545 && break
            echo "Waiting for Geth RPC..." && sleep 3
          done

      - name: Download deployed address artifact
        uses: actions/download-artifact@v4
        with:
          name: lock-address

      - name: Export LOCK_ADDRESS env variable
        run: echo "LOCK_ADDRESS=$(cat lock-address.txt)" >> $GITHUB_ENV

      - name: Run Hardhat test against predeployed contract
        working-directory: hardhat
        run: |
          npx hardhat test test/checkPredeployed.js --network devnet
