name: Test Contracts Against Predeployed Devnet

on:
  workflow_dispatch:

jobs:
  test_contracts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull predeployed devnet image
        run: docker pull ghcr.io/${{ github.repository_owner }}/go-ethereum:devnet-with-contracts

      - name: Start Geth container
        run: |
          docker run -d --name geth-test -p 8545:8545 \
            ghcr.io/${{ github.repository_owner }}/go-ethereum:devnet-with-contracts \
            geth \
              --dev \
              --dev.period 1 \
              --datadir /tmp/devdatadir \
              --http --http.addr 0.0.0.0 --http.port 8545 \
              --http.api eth,net,web3,personal \
              --allow-insecure-unlock

      - name: Wait for Geth
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:8545 >/dev/null; then
              echo "✅ Geth is ready"
              break
            fi
            sleep 3
          done

      - name: Download contract address artifact
        uses: actions/download-artifact@v4
        with:
          name: deployed-lock-address
          path: hardhat

      - name: Show contract address
        run: cat hardhat/deployed-lock-address.txt

      - name: Install Hardhat dependencies
        working-directory: hardhat
        run: npm install

      - name: Run integration tests
        working-directory: hardhat
        run: npx hardhat test --network geth
